In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [3]:
import numpy as np

# 1. Create

In [5]:
data = np.random.rand(2,3,4)
zeros = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [12]:
type(arr)

numpy.ndarray

# 2. Read

In [14]:
# Attributes
shape = data.shape
size = data.size
types = data.dtype

In [22]:
arr = data[0]
slicer = data[0:2]
slicer1 = data[0][1:2]
reverse = data[-1]
singleVal = data[0][0][1]

# 3. Update

In [26]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [28]:
# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [29]:
# Stat Functions - SAPLEMM
sqrt = np.sqrt(25)
ab = np.abs(-1)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [35]:
data[0][0][0] = 700

In [37]:
data.sort()

In [38]:
data

array([[[5.83224590e-01, 5.92214469e-01, 9.75798384e-01, 7.00000000e+02],
        [2.90985168e-01, 8.39184394e-01, 8.43091449e-01, 8.59569656e-01],
        [1.65446039e-01, 4.42447934e-01, 5.24926726e-01, 6.59659606e-01]],

       [[4.80685826e-01, 5.38123884e-01, 6.05772483e-01, 6.17043268e-01],
        [1.29210070e-01, 4.50848025e-01, 8.70199139e-01, 9.59262757e-01],
        [2.98587342e-01, 5.52118455e-01, 5.97572641e-01, 6.02538334e-01]]])

In [39]:
print(data.shape)

(2, 3, 4)


In [41]:
data = data.reshape((2,2,-2))
data.shape

(2, 2, 6)

In [46]:
zeros = np.zeros(8)
print(zeros)
zeros = np.append(zeros, [3,4])
print(zeros)
zeros = np.insert(zeros, 2, 1)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


# 4. Update

In [47]:
data

array([[[5.83224590e-01, 5.92214469e-01, 9.75798384e-01, 7.00000000e+02,
         2.90985168e-01, 8.39184394e-01],
        [8.43091449e-01, 8.59569656e-01, 1.65446039e-01, 4.42447934e-01,
         5.24926726e-01, 6.59659606e-01]],

       [[4.80685826e-01, 5.38123884e-01, 6.05772483e-01, 6.17043268e-01,
         1.29210070e-01, 4.50848025e-01],
        [8.70199139e-01, 9.59262757e-01, 2.98587342e-01, 5.52118455e-01,
         5.97572641e-01, 6.02538334e-01]]])

In [48]:
np.delete(data, 0, axis=1)

array([[[0.84309145, 0.85956966, 0.16544604, 0.44244793, 0.52492673,
         0.65965961]],

       [[0.87019914, 0.95926276, 0.29858734, 0.55211846, 0.59757264,
         0.60253833]]])

In [49]:
np.save("new array", data)

In [50]:
test = np.load("new array.npy")

In [51]:
test

array([[[5.83224590e-01, 5.92214469e-01, 9.75798384e-01, 7.00000000e+02,
         2.90985168e-01, 8.39184394e-01],
        [8.43091449e-01, 8.59569656e-01, 1.65446039e-01, 4.42447934e-01,
         5.24926726e-01, 6.59659606e-01]],

       [[4.80685826e-01, 5.38123884e-01, 6.05772483e-01, 6.17043268e-01,
         1.29210070e-01, 4.50848025e-01],
        [8.70199139e-01, 9.59262757e-01, 2.98587342e-01, 5.52118455e-01,
         5.97572641e-01, 6.02538334e-01]]])